name: Build and Deploy to CH2.0

on:
    push:
      branches: [main]
    #workflow_dispatch:

jobs:
  call-common-workflow:
    uses: hornshoofs/nb-pipelines/.github/workflows/build-pipeline.yaml@main